const musicId = {
    "Vindsvept": {
        "Sleeper": "VMUzqKy3Xec",
        "Sleeper Pt.2": "LcGSBAYlINI",
        "Reverie": "KvZtzD6gqM4",
        "Reverie Pt.2": "L_z7TBLzfEM",
        "Distant": "toYkSo3-McY",
        "The Fae": "8JFG_bKg5lE",
        "Through the Woods we Ran": "yKizp0pDFtA",
        "Through the Woods we Ran Pt.2": "nUkDC--_7E4",
        "Lake of Light": "0qWMgSODSEY",
        "Shimmering in the Shallows": "ZjoxsVV6fFo",
        "Elvenhome": "Nsww3zXsNh0",
        "Wayfarer's Journey": "G0LQ3TjaN9s",
        "Echoes of Ages Past": "dh2FGug7Nto",
        "Onward": "kWtFntVa15k",
        "Dream of Paradie": "PjqqmvlJSZY",
        "Breathe of Life": "bTMl7l-Iq5A",
        "Guiding Stones": "EbMbVmGXsxs",
        "Anima": "OH0si893l3c",
        "Deep Sleep of the Elven King": "LzteZIJios8",
        "To Uncharted Lands": "vtcNTjqPmEU",
        "Deliverance": "kOWbOnDkZIs",
        "Deliverance Pt.2": "bN4bb1iFdeI",
        "Winds Of Will": "lenvZFjEvF8",
        "Light of a New Dawn": "ghxK0SbL3B4",
        "Into the Depths": "7SgWy8lLeWE"
    },
    "DM DOKURO Calamity Mod": {
        "The Tale of a Cruel World": "uYBO_Sk5YiE",
        "Guardian of the Former Seas": "aQFpGpgy2So",
        "Infestation": "OEHwojdJIv4",
        "Return To Slime": "BO533tLd8Ww",
        "Outcast of the Sulphurous Seas": "OagYSQ7dMpM",
        "Raw, Unfiltered Calamity": "9_daB1lYNi0",
        "Silence before the storms": "Q8r3p8luTFc",
        "Pest of the Cosmos": "Abf3Ujxv6YM",
        "Fly of Beelzebub": "6xbyQ53e0js",
        "Storms before the catastrophe": "ND2rC8ZuKfA",
        "Unholy Insurgency": "KPm5yWmkQn0",
        "Servants of the Scourge": "lpys9dRPYmo",
        "Scourge of the Universe": "-ksH1Lvz338",
        "Universal Collapse": "srjhoxEE4Uk",
        "Roar of the Jungle Dragon": "8rEw9sCwo8E",
        "The Step Below Hell": "3Oq62p7udZQ",
        "Heaven's Hell-Sent Gift": "ea2ap54dhRU",
        "Treasures Within The Abomination": "MukpGbEmXcg",
        "wasteland": "kvBc-uH2vFE",
        "sanctuary": "QuC0i5IF1c4",
        "Hadopelagic Pressure": "SJUs9OImsKc",
        "Catastrophes before the calamity": "zYZiXsDGfpU",
        "Stained, Brutal Calamity": "vS2SIGF3qhk",
        "Blessing of the Moon": "zWNuL6hRUb8",
        "Antarctic Reinforcement (Structured Mix)": "Wj3kNKjEKkY",
        "Siren's Call (Seafoam Mix)": "jJah6Q48g3Y",
        "Scourge of the Universe (Eulogy for the Ego)": "fTGmuuyCzuw"
    },
    "A Hat in Time": {
        "Main Theme": "LijvcUx2LNg",
        "Title Screen": "Hf92sTAEHTg",
        "File Select": "ynVjf8l11Fo",
        "New Adventure": "XtDKPGJLyDE",
        "Her Spaceship": "Je4PCeDsHik",
        "Welcome to Mafia Town": "NAQq9tfahZ8",
        "Welcome to Mafia Town (Remix)": "n9wljU5XBjg",
        "Time Piece Released": "5K-vJQO3Jeg",
        "Barrel Battle": "0xu_iFFpFkc",
        "A New Friend in Mafia Town": "cSCzixSYeFw",
        "Mafia Town Is Asleep": "b3OYXpDhC_g",
        "She Came From Outer Space": "NXLn_-G8PJg",
        "So, What's The Plan?": "kxII1d2ZdeQ",
        "Mafia HQ": "LnelrYbmCRQ",
        "The Badge Seller": "4EEVXtLIraw",
        "Mafia Boss' Big Showdown": "Mu7cja2fbZU",
        "Mafia Boss' Big Showdown (Remix)": "7q1TvTjTd0g",
        "Heating Up Mafia Town": "IYK5pG-hW_I",
        "No More Mafia Boss": "ZNp3RNE4794",
        "Scootin' Through Mafia Town": "T8xvrjck3pk",
        "Deadbird Studio Reception": "y2gGEY3sEbQ",
        "Dead Bird Studio": "HP_X5qr3Uh4",
        "You Are Now Legally a Bird": "WDFSIe8fcCM"
    },
    "A Hat in Time (Seal the Deal)": {
        "Bon Voyage!": "fBn1yz03ypw",
        "Ship Shape": "nWsyCIEk62Y",
        "Everyone Rescued": "CWvOEf5UJeY",
        "Peace and Tranquility": "SHvhps47Lmc",
        "Collapsing Time Rift": "fAOn6xZy3FE",
        "Security Breach": "wUKCc0Lu7XQ",
        "Death Wish": "TljApMdkWdo",
        "Killing Two Birds": "C-3WJjy4gRk",
        "Mustache Girl Ex": "YhqAqS6VSnE",
        "Bluefin Tunnels": "8DM4EDjIgTk",
        "Pink Paw Station": "8pajDLucQgM",
        "Fast Food": "_GvB_gCocP4",
    }
}

export default musicId;