const musicId = {
    "BGM": {
        "Vindsvept": {
            "Sleeper": "VMUzqKy3Xec",
            "Sleeper Pt.2": "LcGSBAYlINI",
            "Reverie": "KvZtzD6gqM4",
            "Reverie Pt.2": "L_z7TBLzfEM",
            "Distant": "toYkSo3-McY",
            "The Fae": "8JFG_bKg5lE",
            "Through the Woods we Ran": "yKizp0pDFtA",
            "Through the Woods we Ran Pt.2": "nUkDC--_7E4",
            "Lake of Light": "0qWMgSODSEY",
            "Shimmering in the Shallows": "ZjoxsVV6fFo",
            "Elvenhome": "Nsww3zXsNh0",
            "Wayfarer's Journey": "G0LQ3TjaN9s",
            "Echoes of Ages Past": "dh2FGug7Nto",
            "Onward": "kWtFntVa15k",
            "Dream of Paradie": "PjqqmvlJSZY",
            "Breathe of Life": "bTMl7l-Iq5A",
            "Guiding Stones": "EbMbVmGXsxs",
            "Anima": "OH0si893l3c",
            "Deep Sleep of the Elven King": "LzteZIJios8",
            "To Uncharted Lands": "vtcNTjqPmEU",
            "Deliverance": "kOWbOnDkZIs",
            "Deliverance Pt.2": "bN4bb1iFdeI",
            "Winds Of Will": "lenvZFjEvF8",
            "Light of a New Dawn": "ghxK0SbL3B4",
            "Into the Depths": "7SgWy8lLeWE"
        }
    },
    "Game OST": {
        "DM DOKURO Calamity Mod": {
            "The Tale of a Cruel World": "uYBO_Sk5YiE",
            "Guardian of the Former Seas": "aQFpGpgy2So",
            "Infestation": "OEHwojdJIv4",
            "Return To Slime": "BO533tLd8Ww",
            "Outcast of the Sulphurous Seas": "OagYSQ7dMpM",
            "Raw, Unfiltered Calamity": "9_daB1lYNi0",
            "Silence before the storms": "Q8r3p8luTFc",
            "Pest of the Cosmos": "Abf3Ujxv6YM",
            "Fly of Beelzebub": "6xbyQ53e0js",
            "Storms before the catastrophe": "ND2rC8ZuKfA",
            "Unholy Insurgency": "KPm5yWmkQn0",
            "Servants of the Scourge": "lpys9dRPYmo",
            "Scourge of the Universe": "-ksH1Lvz338",
            "Universal Collapse": "srjhoxEE4Uk",
            "Roar of the Jungle Dragon": "8rEw9sCwo8E",
            "The Step Below Hell": "3Oq62p7udZQ",
            "Heaven's Hell-Sent Gift": "ea2ap54dhRU",
            "Treasures Within The Abomination": "MukpGbEmXcg",
            "wasteland": "kvBc-uH2vFE",
            "sanctuary": "QuC0i5IF1c4",
            "Hadopelagic Pressure": "SJUs9OImsKc",
            "Catastrophes before the calamity": "zYZiXsDGfpU",
            "Stained, Brutal Calamity": "vS2SIGF3qhk",
            "Blessing of the Moon": "zWNuL6hRUb8",
            "Antarctic Reinforcement (Structured Mix)": "Wj3kNKjEKkY",
            "Siren's Call (Seafoam Mix)": "jJah6Q48g3Y",
            "Scourge of the Universe (Eulogy for the Ego)": "fTGmuuyCzuw"
        },
        "A Hat in Time": {
            "Main Theme": "LijvcUx2LNg",
            "Title Screen": "Hf92sTAEHTg",
            "File Select": "ynVjf8l11Fo",
            "New Adventure": "XtDKPGJLyDE",
            "Her Spaceship": "Je4PCeDsHik",
            "Welcome to Mafia Town": "NAQq9tfahZ8",
            "Welcome to Mafia Town (Remix)": "n9wljU5XBjg",
            "Time Piece Released": "5K-vJQO3Jeg",
            "Barrel Battle": "0xu_iFFpFkc",
            "A New Friend in Mafia Town": "cSCzixSYeFw",
            "Mafia Town Is Asleep": "b3OYXpDhC_g",
            "She Came From Outer Space": "NXLn_-G8PJg",
            "So, What's The Plan?": "kxII1d2ZdeQ",
            "Mafia HQ": "LnelrYbmCRQ",
            "The Badge Seller": "4EEVXtLIraw",
            "Mafia Boss' Big Showdown": "Mu7cja2fbZU",
            "Mafia Boss' Big Showdown (Remix)": "7q1TvTjTd0g",
            "Heating Up Mafia Town": "IYK5pG-hW_I",
            "No More Mafia Boss": "ZNp3RNE4794",
            "Scootin' Through Mafia Town": "T8xvrjck3pk",
            "Deadbird Studio Reception": "y2gGEY3sEbQ",
            "Dead Bird Studio": "HP_X5qr3Uh4",
            "You Are Now Legally a Bird": "WDFSIe8fcCM",
            "The Ratings Are In": "DXN8tnErII0",
            "Picture Perfect": "Psquwscyxbg",
            "Picture Perfect (Remix)": "pedMb-6oA3M",
            "Murder On the Owl Express": "szog4XxsPTo",
            "Who Dun It": "SNoYRum25JM",
            "Tick Tock": "_BlvvwHjVWs",
            "The Phone's Ringing": "PGjqdXoixLg",
            "Metal Bork": "xBErysNcUjo",
            "The Conductor's Train": "lI2noF2P1x8",
            "Train Rush": "e9zvAVH-tsw",
            "Trainwreck Of Electro Swing (Remix)": "nkjVscSRNtY",
            "The Big Parade": "4ivEuF_1LAA",
            "Turn on the Pyrotechnics": "RjZWwvME02o",
            "Dead Bird Studio Basement": "H2vwu2i4ouM",
            "Dead Bird Studio is Closed": "IcBnWDXajjs",
            "The Annual Bird Movie Award": "YaHFifJkndE",
            "The Battle of Award 42": "Yz9aBqJo3ys",
            "Heart To Heart": "D01X8-J80iE",
            "Subcon Forest": "aFsS_65zz4Y",
            "Scootin' Through Subcon Forest": "-gEDZLI28I0",
            "Snatcher's Contractual Obligations": "LxzCTrF0fCc",
            "Oh It's You": "JF2dydt5c9o",
            "Subcon Village": "nJj8x2brfgI",
            "Subcon Village (Remix)": "tf7eJqleI9U",
            "The Fire Spirits": "qG7-uNQUmEQ",
            "The Subcon Caves": "_BPZOiXH_58",
            "Toilet Of Doom": "EOh9Twq6Lig",
            "A Forsaken Place": "C4lVlw9zeds",
            "Entering Vanessa Manor": "sgR5cHrS0S8",
            "Vanessa Wants To Play": "OEjZFvJy8oI",
            "You're Safe Now": "qQEWhjcWIJs",
            "Your Contract Has Expired": "CMKNjCc12fs",
            "Your Contract Has Expired (Remix)": "8kZIINJcQNw",
            "The Tower of the Goats": "NYR-lzQZM5U",
            "Alpine Skyline": "ZQaPTcSXLmk",
            "The Birdhouse Peak": "cSkWCa379DE",
            "The Lava Cake Peak": "m26hRmFoyi",
            "The Windmill Peak": "MDf78wVI-Yk",
            "The Twilight Bell Peak": "XtyQ_qf6kAY",
            "Alpine Skyline at Night": "O1zm_9Moftw",
            "The Weather Has Cleared": "2Pt3Q5yxaAY",
            "Clocktowers Beneath The Sea": "bDgYhV17Rpo",
            "Scootin' Through Clocktowers Beneath The Sea": "bX6TjxSmgGw",
            "Clocktowers Beneath The Sea (Remix)": "em5-2xpDJGg",
            "Mafia of Cooks Time Rift": "KhdtAxhpKfs",
            "Battle of the Birds Time Rift": "k9UWoVSB2ig",
            "Subcon Forest Time Rift": "RKnwapQ9tQQ",
            "Alpine Skyline Time Rift": "GeN0JlzIX9Y",
            "Roll the Slots": "vL8NkTB9pqQ",
            "Judge, Jury and Executioner": "p7RYEAya2h8",
            "You Are All Bad Guys": "eaiK4eLaizI",
            "Get Lost": "4d8id05oKqk",
            "Little Help From My Friends": "_Lp8hrm_4MQ",
            "Goodbye Everyone": "OfecnYC2E2I",
            "The End": "Okb5qTVbhbo"
        },
        "A Hat in Time (Seal the Deal)": {
            "Bon Voyage!": "fBn1yz03ypw",
            "Ship Shape": "nWsyCIEk62Y",
            "Everyone Rescued": "CWvOEf5UJeY",
            "Peace and Tranquility": "SHvhps47Lmc",
            "Collapsing Time Rift": "fAOn6xZy3FE",
            "Security Breach": "wUKCc0Lu7XQ",
            "Death Wish": "TljApMdkWdo",
            "Killing Two Birds": "C-3WJjy4gRk",
            "Mustache Girl Ex": "YhqAqS6VSnE",
            "Bluefin Tunnels": "8DM4EDjIgTk",
            "Pink Paw Station": "8pajDLucQgM",
            "Fast Food": "_GvB_gCocP4",
        },
        "The Binding of Isaac": {
            "Those Responsible": "VJNQWpVf8Zg",
            "In The Beginning...": "zN4_9kZ53bo",
            "The Binding of Isaac": "jBfom3wYOuY",
            "Unknown Depths Below": "HapnGxj5joo",
            "Sacrificial": "FwbK0Y1qnOY",
            "Conflicted": "PUotNxlI1dE",
            "Divine Combat": "UaxjRoDrpus",
            "Pride": "Tbg8B2lGjVU",
            "Peace Be With You": "v-LHc8Yhr3s",
            "Agony": "OdB3HddwF0I",
            "Repentant": "07L4M_RWIgQ",
            "Respite": "8NXCHbzAXvw",
            "$4cr1f1c14|_": "p3Wm1hH5FFs",
            "Dreadful": "6Y2A4kDq8ns",
            "Burning Ambush": "3D5W66u-XgI",
            "Greed": "XbWDWoC6X4I",
            "Thine Wrath": "_q9ZC-UwViM",
            "Apostate": "JcBtmCW1_ss",
            "Hereafter": "Hakc5uzSY4A",
            "Temptation": "r6U3IrR0b3w",
            "The Pact": "80Lu0Umk2k0",
            "...Be Done": "Zj9Ck3mNP4o",
            "Absolution": "p0QC_is8a4Q",
            "Ultimate Reward": "DSinYB94yXc",
            "End Times": "l02S0ZiNt44",
            "A Mourner Unto Sheol": "irnikRf7hEY",
            "Enmity of the Dark Lord": "PhMj9tMtRs8",
            "Penance": "Ey2TOGVZdlc",
            "Atonement": "TnMV1yPi7Z0",
            "Latter Days": "jmr1l130HOs",
            "Lament of the Angel": "kB7z4eXt6z8",
            "Unholy Assault": "Rnurn50PT5M",
            "Crusade": "PUJUFXtbLqU",
            "Serenity": "G_SFouLA2qY",
            "Tomes": "qFah9BL4Etg",
            "The Wages of Faith": "ALC0sn9rSro",
            "My Innermost Apocalypse": "H4noeZx9W6s",
            "The Clubbing of Isaac (Remix)": "9GmDAj0nL8c",
            "Atempause (Remix)": "6AOVsSksNmI"
        },
        "The Binding of Isaac (Rebirth)": {
            "Genesis 22:10 (Title)": "QQSH-3WLPZ0",
            "Diptera Sonata": "G92HDJocGtk",
            "Crusade (Basic Boss Fight)": "hHq0fEdJn1s",
            "Sodden Hollow (Caves)": "DDAr7eKBzCw",
            "The Forgotten (Secret Room)": "_Mj1o3YOsWk",
            "Abyss (The Depths)": "gxU5eUCjxc0",
            "Matricide (Mom Fight)": "_ipiroyqDu8",
            "The Calm": "7U929k0xkAY",
            "Viscera (Womb)": "i5hdVcvi9BM",
            "Ventricle (Womb Fight)": "BjaldNf2X9o",
            "Acceptance (You Died)": "5cstYiU6srQ",
            "Anima Vendit (Deal With the Evil)": "0O4v1sieM3E",
            "Duress (Sheol)": "ps7U4pMauIs",
            "Hericide (Satan Fight)": "O1NLigOmsWA",
            "Murmur of the Harvestman (Store)": "lXf-B_DiJ6Q",
            "Empty Vessels (Angel Room)": "Me4cPXaKKB4",
            "Everlasting Hymn (Cathedral)": "8uWjOwDsn-U",
            "Infanticide (Isaac Fight)": "Yyna4f_SPD8",
            "Tome of Knowledge (Library)": "8AKPhHgBtS0",
            "Periculum (The Cellar)": "lDtUpSxjrQo",
            "Capiticus Calvaria (Catacombs)": "jXUGXpR2J6E",
            "When Blood Dries (Necropolis)": "IQESTuCL8BI",
            "Sketches of Pain (Chest Room)": "ST41otsSmh4",
            "Ascension (Chest Fight)": "-zceNWFFluY",
            "Devoid (Dark Room)": "miw4fjuR1Rw",
            "The Fallen Angel (Dark Room Fight)": "anZtzvYQc-",
            "Tribute (Credits)": "qSd8NTpRAgs",
            "Genesis 13:37 (Retro Beats)": "Dn3sJeYdejc",
            "Hush (Jesus Loves Uke)": "tnpzaFV4bk0",
            "Descensum (Bonus Track)": "NhevmuWB4Bk",
            "He's the Number One (Bonus Track)": "USifllKQd3Y",
            "Ambush": "OQuXBDDqFos"
        }
    }
}

export default musicId;